spring:
  application:
    name: HelloSpring

  datasource:
    url: jdbc:postgresql://localhost:5432/isi_hello_spring
    username: postgres
    password: Barthy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
